CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE libros(
	id	INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(200) NOT NULL,
	imagen TEXT NOT NULL
)ENGINE=INNODB;

INSERT INTO libros VALUES 
	(NULL, 'libro a', 'libroA.jpg'),
	(NULL, 'libro b', 'libroB.jpg');

SELECT * FROM libros;


CREATE TABLE editoriales(
	id	INT AUTO_INCREMENT PRIMARY KEY,
	editorial VARCHAR(200) NOT NULL,
	telefono CHAR(9) NULL,
	direccion VARCHAR(100) NULL
)ENGINE=INNODB;

SELECT * FROM editoriales;